### ISSUE TITLE
Consider removing distinction between live and installation .ISO

### ISSUE THREAD

**Issue by digitalethics** [openSUSE/get-o-o#16]
I find the distinction between separate live and installation .ISOs obsolete in a modern operating system context. Many distributions with an explicit focus on usability have given up on this distinction and offer one installation medium which simultaneously functions as a live installer with persistant mode capabilities (e.g. changes made during the live run such as entering a WiFi password should be preserved after installation) to reduce post-installation setup time.

**Comment by hellcp** [comment]
> I find the distinction between separate live and installation .ISOs obsolete in a modern operating system context. Many distributions with an explicit focus on usability have given up on this distinction and offer one installation medium which simultaneously functions as a live installer with persistant mode capabilities (e.g. changes made during the live run such as entering a WiFi password should be preserved after installation) to reduce post-installation setup time.

There are a few reasons why we can't do this:
1. We include a hefty warning you should **never** use Live medium for installing [[1]](https://github.com/openSUSE/get-o-o/blob/main/_data/locales/en.yml#L46-L49)
2. YaST Installation isn't a good Live Installer software, since it cannot do the things you listed, and we do not have an existing project that would allow for those capabilities
3. We need a way to give users an option to install the distribution without online access, which is what the DVD installer is for.

Here as a sidenote, reducing post installation setup time would be easier with a DE tailored firstboot setup tool like GNOME Initial Setup, however Plasma does not provide such a tool yet, so we don't make use of GIS either

**If** you want to change those things, don't bother changing them here, reach out to openSUSE Factory mailing list and IRC channel with some plan and start implementing those things yourself or with a small group of people you excite about the prospect. This is only a website marketing the efforts, not a place for development of the distributions ;)
