### ISSUE TITLE
JeOS rename to Minimal was Live images and JeOS are too hidden

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/get-o-o#47]
The live images and JeOS are very well hidden and can only be reached by clicking a link in text after "Can't find what you are looking for?", which is a wording used on other web sites to redirect to support pages.

Please fix this, otherwise they're pretty much wasted effort.

**Comment by vmoutoussamy** [comment]
I highly agree that JeOS is too hidden as of now. Also "Alternative Downloads" in the following sentence "Can't find what you are looking for? Check out Alternative Downloads for the JeOS, Live image download options." might not be the best word: 

* I'm used to search for "software alternative" to look for different software with the same feature sets or purpose (https://alternativeto.net/). In that regard I don't think JeOS images are alternative of regular ISOs. I mean the usecases are be too different
* To my non-native english hear, "Alternative Downloads" means "different download mirror".

**Comment by vmoutoussamy** [comment]
but I guess the word Alternative is "fine" since Fedora is using it: https://alt.fedoraproject.org/en/

**Comment by hellcp** [comment]
Yeah, I'm open to suggestions, I did think it may be too hidden to just mention alternative downloads, which is why I also mention the headers of every type of image we have there

**Comment by Vogtinator** [comment]
IMO it's not too much to just put the live images below the Offline Image and Network Image options, but for JeOS a separate section might be better. Issue is that each arch has a section, so just adding another one for JeOS wouldn't really make sense either, because it's not an architecture.

What about just embedding the entire "Alternative Downloads" page into the downloads tab?

**Comment by hellcp** [comment]
That makes the entire documentation about downloading and installing the distribution go so far down, nobody's gonna notice it's there, not to mention that does seem very overwhelming to just put every variant before every new user, making it really hard for them to choose what to download.

**Comment by Vogtinator** [comment]
Then revert to the older design of having separate tabs for DVD/Live/JeOS?

**Comment by hellcp** [comment]
That had the same issue of being overwhelming after adding the overview tab too, since suddenly there was no default

**Comment by vmoutoussamy** [comment]
I also miss the former design with meaningful tab for the different flavors and would like to revert to it. Because 1) JeOS was visible, 2) The overall download page was clearer.

The problem here, is that we are seeing a lot of issue with this change and it's not helping the overall UX + UI consistency. 
Please let me know where such discussion could be done, until then I'll write my thoughts below:

IMHO https://get.opensuse.org/ should just stick to be a practical download page... so having the full overview of TW and MicroOS features by default doesn't make sense. It's better to have real download links in the default tab and why not more information or download links in other tab.

If I'm comparing getfedora and get.openuse for downloading a regular x86_64 server distro: 
- 1) Go to https://getfedora.org/, 2) See the server section and click on "download now", 3) see the architecture section and select regular/netinstall and click download
- 2) Go to https://get.opensuse.org/, 2) see the server section and click on "Server", 3) see Leap and click on "View Leap 15.2" (sic), 4) see the overview and the download button but also see the "download" tab, 5) See only the x86_64 architecture and select regular/netinstall and click download.

**Comment by hellcp** [comment]
Yeah, I meant to add Download/Learn more links to server/desktop pages too, just didn't do that yet

**Comment by hellcp** [comment]
Keep in mind, get.opensuse.org was split from software.o.o to allow it to basically replace distribution portals on the wiki, download pages on software.o.o and the content from the www.o.o, which due to being in different places keeps diverging and not being accurate to the reality. We kind of do need a single place to talk about distributions that doesn't fall out of maintenance.

**Comment by Vogtinator** [comment]
Just today there's a reddit post asking whether there are also live images available: https://old.reddit.com/r/openSUSE/comments/nmqcmi/how_to_live_boot_from_a_tw_usb_stick/

Obviously the link was just very well hidden.

Can this please get fixed before the 15.3 release?

**Comment by Vogtinator** [comment]
Great, I see that you also changed the wording to "We also have JeOS, Live images. Check out Alternative Downloads!".

It's an improvement, but it only works when actually using the "Desktop" and "Server" options and not going straight to the TW or Leap download pages. That's a bit like "magic", because it makes options appear and vanish depending how you got to the same page...

**Comment by Vogtinator** [comment]
Any news here? There's another case where someone couldn't find the live images:

https://old.reddit.com/r/openSUSE/comments/tt5a0c/a_question_before_installing_the_chameleon/

**Comment by hellcp** [comment]
I think the best  way to actually fix this would be to finally finish the revamp of www.opensuse.org, so we have people going to Desktop and Server pages first, instead of landing on distro pages. If you have some better ideas, I would love to hear them!
